version: 0.0
os: linux
files:
  - source: ./webapp
    destination: /home/ubuntu/webapp
hooks:
  ApplicationStop:
   - location: codedeploy/applicationStop.sh
     timeout: 180
     runas: ubuntu
  BeforeInstall:
   - location: codedeploy/beforeInstall.sh
     timeout: 180
     runas: ubuntu
  AfterInstall:
   - location: codedeploy/afterInstall.sh
     timeout: 180
     runas: ubuntu
  ApplicationStart:
   - location: codedeploy/applicationStart.sh
     runas: ubuntu
     timeout: 180