version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu
hooks:
  ApplicationStop:
   - location: ./codeDeploy/applicationStop.sh
     timeout: 180
     runas: ubuntu
  BeforeInstall:
   - location: ./codedeploy/beforeInstall.sh
     timeout: 180
     runas: ubuntu
  AfterInstall:
   - location: Scripts/afterInstall.sh
     timeout: 180
     runas: ubuntu
  ApplicationStart:
   - location: Scripts/applicationStart.sh
     runas: ubuntu
     timeout: 180