version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu
hooks:
  AfterInstall:
   - location: Scripts/afterInstall.sh
     timeout: 300
     runas: ubuntu
  ApplicationStart:
   - location: Scripts/applicationStart.sh
     runas: ubuntu
     timeout: 300