name: Deploy Webapp

on:
  pull_request:
    types: [ closed ]
    branches:
      - 'main'

env:
  artifact_name: webapp-${{ github.sha }}.zip
  s3_bucket_name: codedeploy.jing.yang.prod

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.GHACTIONS_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.GHACTIONS_AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: upload to s3
      run: |
        pwd
        mkdir webapp
        cd webapp
        cp ../*.json .
        cp ../*.md .
        cp ../*.js .
        cp -r ../models .
        cp -r ../routes .
        cp -r ../services .
        cp -r ../test .
        cp -r ../.github .
        cd ..
        mkdir codedeploy_artifact
        zip -r ${{ env.artifact_name }} webapp appspec.yml codedeploy
        pwd
        ls -al
        mv ${{ env.artifact_name }} codedeploy_artifact/
        pwd
        ls -al
        cd codedeploy_artifact
        pwd
        ls -al
        cd ..
        echo "aws s3 upload start"
        aws s3 sync ./codedeploy_artifact s3://${{ env.s3_bucket_name }}
        echo "aws s3 upload complete"

    - name: deploy
      run: |
          output=$(aws deploy create-deployment \
          --application-name csye6225-webapp \
          --deployment-config-name CodeDeployDefault.OneAtATime \
          --deployment-group-name csye6225-webapp-deployment \
          --description "CSYE6225 CodeDeploy" \
          --s3-location bucket=${{ env.s3_bucket_name }},key=${{ env.artifact_name }},bundleType=zip \
          --region us-east-1 \
          --output json)
          echo $output
          dId=$(echo $output | jq -r '.deploymentId')
          aws deploy wait deployment-successful --deployment-id $dId