name: Deploy CI

on:
  pull_request:
    types: [ closed ]
    branches:
      - 'main'

env:
  artifact_name: webapp-${{ github.sha }}.tar
  s3_bucket_name: codedeploy.jing.yang.prod

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: us-east-1

    - name: upload to s3
      run: |
        pwd
        mkdir webapp_s3
        cp ./*.js webapp_s3
        cp ./README.md webapp_s3
        cp ./package.json webapp_s3
        cp -r ./models webapp_s3
        cp -r ./routes webapp_s3
        cp -r ./services webapp_s3
        ls -alR
        echo "tar ${{ env.artifact_name }} start"
        tar -cvf ${{ env.artifact_name }} webapp_s3
        echo "tar ${{ env.artifact_name }} complete"
        echo "aws s3 upload start"
        aws s3 sync ${{ env.artifact_name }} s3://${{ env.s3_bucket_name }}
        echo "aws s3 upload complete"

    - name: deploy
      run: |
          output=$(aws deploy create-deployment \
          --application-name webapp \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --deployment-group-name webapp-group \
          --description "CSYE6225 - CodeDeploy" \
          --s3-location bucket=${s3_bucket_name},key=webapp.tar,bundleType=tar \
          --region us-east-1 \
          --output json)
          echo $output
          dId=$(echo $output | jq -r '.deploymentId')
          aws deploy wait deployment-successful --deployment-id $dId